project_root: /Users/paoloolivieri/discogs_tools_refactor
raw_root: /Users/paoloolivieri/discogs_store/raw

# deterministic RUN ID of the session
run_id: ${moment(session_time).format("YYYYMMDD_HHmmss")}

# Trino
trino_container: trino
trino_catalog: hive
trino_schema: discogs

# defaults pipeline (overridable with CLI & -p)
run_mode: prod
do_download: true
